# Introduction to DataFrames
**This is from the excellent Julia tutorial by [Bogumił Kamiński](http://bogumilkaminski.pl/about/)** <br>
Entire tutorial available [here](https://github.com/bkamins/Julia-DataFrames-Tutorial)


In [1]:
using DataFrames

## Split-apply-combine

### Grouping a data frame

In [2]:
x = DataFrame(id=[1,2,3,4,1,2,3,4], id2=[1,2,1,2,1,2,1,2], v=rand(8))

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     2      2  0.515204
   3 │     3      1  0.3344
   4 │     4      2  0.999389
   5 │     1      1  0.787124
   6 │     2      2  0.287537
   7 │     3      1  0.975704
   8 │     4      2  0.239029

In [3]:
groupby(x, :id)

GroupedDataFrame with 4 groups based on key: id
First Group (2 rows): id = 1
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124
⋮
Last Group (2 rows): id = 4
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.999389
   2 │     4      2  0.239029

In [4]:
groupby(x, [])

GroupedDataFrame with 1 group based on key: 
First Group (8 rows): 
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     2      2  0.515204
   3 │     3      1  0.3344
   4 │     4      2  0.999389
   5 │     1      1  0.787124
   6 │     2      2  0.287537
   7 │     3      1  0.975704
   8 │     4      2  0.239029

In [5]:
gx2 = groupby(x, [:id, :id2])

GroupedDataFrame with 4 groups based on keys: id, id2
First Group (2 rows): id = 1, id2 = 1
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124
⋮
Last Group (2 rows): id = 4, id2 = 2
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.999389
   2 │     4      2  0.239029

In [6]:
parent(gx2) # get the parent DataFrame 

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     2      2  0.515204
   3 │     3      1  0.3344
   4 │     4      2  0.999389
   5 │     1      1  0.787124
   6 │     2      2  0.287537
   7 │     3      1  0.975704
   8 │     4      2  0.239029

In [7]:
vcat(gx2...) # back to the DataFrame, but in a different order of rows than the original

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124
   3 │     2      2  0.515204
   4 │     2      2  0.287537
   5 │     3      1  0.3344
   6 │     3      1  0.975704
   7 │     4      2  0.999389
   8 │     4      2  0.239029

In [8]:
DataFrame(gx2) # the same

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124
   3 │     2      2  0.515204
   4 │     2      2  0.287537
   5 │     3      1  0.3344
   6 │     3      1  0.975704
   7 │     4      2  0.999389
   8 │     4      2  0.239029

In [9]:
DataFrame(gx2, keepkeys=false) # drop grouping columns when creating a data frame

8×1 DataFrame
 Row │ v         
     │ Float64   
─────┼───────────
   1 │ 0.0278714
   2 │ 0.787124
   3 │ 0.515204
   4 │ 0.287537
   5 │ 0.3344
   6 │ 0.975704
   7 │ 0.999389
   8 │ 0.239029

In [10]:
groupcols(gx2) # vector of names of grouping variables

2-element Vector{Symbol}:
 :id
 :id2

In [11]:
valuecols(gx2) # and non-grouping variables

1-element Vector{Symbol}:
 :v

In [12]:
groupindices(gx2) # group indices in parent(gx2)

8-element Vector{Union{Missing, Int64}}:
 1
 2
 3
 4
 1
 2
 3
 4

In [13]:
kgx2 = keys(gx2)

4-element DataFrames.GroupKeys{GroupedDataFrame{DataFrame}}:
 GroupKey: (id = 1, id2 = 1)
 GroupKey: (id = 2, id2 = 2)
 GroupKey: (id = 3, id2 = 1)
 GroupKey: (id = 4, id2 = 2)

You can index into a `GroupedDataFrame` like to a vector or to a dictionary.
The second form acceps `GroupKey`, `NamedTuple` or a `Tuple`

In [14]:
gx2

GroupedDataFrame with 4 groups based on keys: id, id2
First Group (2 rows): id = 1, id2 = 1
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124
⋮
Last Group (2 rows): id = 4, id2 = 2
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.999389
   2 │     4      2  0.239029

In [15]:
k = keys(gx2)[1]

GroupKey: (id = 1, id2 = 1)

In [16]:
ntk = NamedTuple(k)

(id = 1, id2 = 1)

In [17]:
tk = Tuple(k)

(1, 1)

the operations below produce the same result and are fast

In [18]:
gx2[1]

2×3 SubDataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124

In [19]:
gx2[k]

2×3 SubDataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124

In [20]:
gx2[ntk]

2×3 SubDataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124

In [21]:
gx2[tk]

2×3 SubDataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.0278714
   2 │     1      1  0.787124

handling missing values

In [22]:
x = DataFrame(id = [missing, 5, 1, 3, missing], x = 1:5)

5×2 DataFrame
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │       5      2
   3 │       1      3
   4 │       3      4
   5 │ missing      5

In [23]:
groupby(x, :id) # by default groups include mising values and are not sorted

GroupedDataFrame with 4 groups based on key: id
First Group (1 row): id = 1
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      1      3
⋮
Last Group (2 rows): id = missing
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │ missing      5

In [24]:
groupby(x, :id, sort=true, skipmissing=true) # but we can change it

GroupedDataFrame with 3 groups based on key: id
First Group (1 row): id = 1
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      1      3
⋮
Last Group (1 row): id = 5
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      5      2

### Performing transformations by group using `combine`, `select`, `select!`, `transform`, and `transform!`

In [26]:
using Pkg
using Statistics
using Pipe

The **Pipe** package allows you to improve the Pipe operator |> in Julia Base.

Chaining (or "piping") allows to string together multiple function calls in a way that is at the same time compact and readable. It avoids saving intermediate results without having to embed function calls within one another.

With the chain operator |> instead, the code to the right of |> operates on the result from the code to the left of it. In practice, what is on the left becomes the argument of the function call(s) that is on the right.

Chaining is very useful in data manipulation. Let's assume that you want to use the following (silly) functions operate one after the other on some data and print the final result:

In [43]:
add6(a) = a+6; div4(a) = 4/a;

In [44]:
# You could either introduce temporary variables or embed the function calls:
a = 2; b = add6(a); c = div4(b); println(c) # 0.5
println(div4(add6(a)))

0.5
0.5


With piping you can write instead:

In [45]:
a |> add6 |> div4 |> println

0.5


Pipes in Base are very limited, in the sense that support only functions with one argument and only a single function at a time.

Conversely, the Pipe package together with the `@pipe` macro hoverrides the |> operator allowing you to use functions with multiple arguments (and there you can use the underscore character `_` as placeholder for the value on the LHS) and multiple functions, e.g.:

`
addX(a,x) = a+x; divY(a,y) = a/y  
@pipe a |> addX(_,6) + divY(4,_) |> println # 10.0
`

In [53]:
ENV["LINES"] = 15 # reduce the number of rows in the output

15

Create a DataFrame with id column randomly selected from a--d and v being a random uniform number in [0,1]

In [58]:
x = DataFrame(id=rand('a':'d', 100), v=rand(100))

100×2 DataFrame
 Row │ id    v         
     │ Char  Float64   
─────┼─────────────────
   1 │ b     0.865976
   2 │ a     0.133306
   3 │ d     0.13789
  ⋮  │  ⋮        ⋮
  98 │ b     0.666072
  99 │ c     0.627473
 100 │ b     0.436655
        94 rows omitted

In [59]:
# apply a function to each group of a data frame
# combine keeps as many rows as are returned from the function
@pipe x |> groupby(_, :id) |> combine(_, :v=>mean)

4×2 DataFrame
 Row │ id    v_mean   
     │ Char  Float64  
─────┼────────────────
   1 │ b     0.531336
   2 │ a     0.390951
   3 │ d     0.546437
   4 │ c     0.462542

In [60]:
x.id2 = axes(x, 1)

Base.OneTo(100)

In [61]:
# select and transform keep as many rows as are in the source data frame and in correct order
# additionally transform keeps all columns from the source
@pipe x |> groupby(_, :id) |> transform(_, :v=>mean)

100×4 DataFrame
 Row │ id    v          id2    v_mean   
     │ Char  Float64    Int64  Float64  
─────┼──────────────────────────────────
   1 │ b     0.865976       1  0.531336
   2 │ a     0.133306       2  0.390951
   3 │ d     0.13789        3  0.546437
  ⋮  │  ⋮        ⋮        ⋮       ⋮
  98 │ b     0.666072      98  0.531336
  99 │ c     0.627473      99  0.462542
 100 │ b     0.436655     100  0.531336
                         94 rows omitted

In [62]:
# note that combine reorders rows by group of GroupedDataFrame
@pipe x |> groupby(_, :id) |> combine(_, :id2, :v=>mean)

100×3 DataFrame
 Row │ id    id2    v_mean   
     │ Char  Int64  Float64  
─────┼───────────────────────
   1 │ b         1  0.531336
   2 │ b        10  0.531336
   3 │ b        16  0.531336
  ⋮  │  ⋮      ⋮       ⋮
  98 │ c        92  0.462542
  99 │ c        94  0.462542
 100 │ c        99  0.462542
              94 rows omitted

In [63]:
# we give a custom name for the result column
@pipe x |> groupby(_, :id) |> combine(_, :v=>mean=>:res)

4×2 DataFrame
 Row │ id    res      
     │ Char  Float64  
─────┼────────────────
   1 │ b     0.531336
   2 │ a     0.390951
   3 │ d     0.546437
   4 │ c     0.462542

In [64]:
# you can have multiple operations
@pipe x |> groupby(_, :id) |> combine(_, :v=>mean=>:res1, :v=>sum=>:res2, nrow=>:n)

4×4 DataFrame
 Row │ id    res1      res2      n     
     │ Char  Float64   Float64   Int64 
─────┼─────────────────────────────────
   1 │ b     0.531336  14.8774      28
   2 │ a     0.390951   3.90951     10
   3 │ d     0.546437  17.486       32
   4 │ c     0.462542  13.8763      30

Additional notes:
* `select!` and `transform!` perform operations in-place
* The general syntax for transformation is `source_columns => function => target_column`
* if you pass multiple columns to a function they are treated as positional arguments
* `ByRow` and `AsTable` work exactly like discussed for operations on data frames in 05_columns.ipynb
* you can automatically groupby again the result of `combine`, `select` etc. by passing `ungroup=false` keyword argument to them
* similarly `keepkeys` keyword argument allows you to drop grouping columns from the resulting data frame

It is also allowed to pass a function to all these functions (also - as a special case, as a first argument). In this case the return value can be a table. In particular it allows for an easy dropping of groups if you return an empty table from the function.

If you pass a function you can use a `do` block syntax. In case of passing a function it gets a `SubDataFrame` as its argument.

Here is an example:

In [65]:
combine(groupby(x, :id)) do sdf
    n = nrow(sdf)
    n < 25 ? DataFrame() : DataFrame(n=n) # drop groups with low number of rows
end

3×2 DataFrame
 Row │ id    n     
     │ Char  Int64 
─────┼─────────────
   1 │ b        28
   2 │ d        32
   3 │ c        30

You can also produce multiple columns in a single operation, e.g.:

In [66]:
df = DataFrame(id=[1,1,2,2], val=[1,2,3,4])

4×2 DataFrame
 Row │ id     val   
     │ Int64  Int64 
─────┼──────────────
   1 │     1      1
   2 │     1      2
   3 │     2      3
   4 │     2      4

In [67]:
@pipe df |> groupby(_, :id) |> combine(_, :val => (x -> [x]) => AsTable)

2×3 DataFrame
 Row │ id     x1     x2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      2
   2 │     2      3      4

In [68]:
@pipe df |> groupby(_, :id) |> combine(_, :val => (x -> [x]) => [:c1, :c2])

2×3 DataFrame
 Row │ id     c1     c2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      2
   2 │     2      3      4

### Aggregation of a data frame using `mapcols`

In [74]:
x = DataFrame(rand(10, 10), :auto)

10×10 DataFrame
 Row │ x1        x2         x3         x4        x5          x6         x7     ⋯
     │ Float64   Float64    Float64    Float64   Float64     Float64    Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.182812  0.612727   0.753226   0.680121  0.482326    0.598521   0.4567 ⋯
   2 │ 0.283253  0.0679383  0.654286   0.688255  0.84735     0.182331   0.5635
   3 │ 0.908733  0.480239   0.591067   0.518461  0.306559    0.885562   0.7646
  ⋮  │    ⋮          ⋮          ⋮         ⋮          ⋮           ⋮         ⋮   ⋱
   8 │ 0.181397  0.339051   0.0182818  0.815847  0.00507345  0.95117    0.9096
   9 │ 0.494481  0.565876   0.52434    0.629434  0.179599    0.814441   0.2759 ⋯
  10 │ 0.623516  0.34997    0.742189   0.128856  0.124592    0.864321   0.7597
                                                    4 columns and 4 rows omitted

Return a DataFrame where each column of df is transformed using function f. f must return AbstractVector objects all with the same length or scalars (all values other than AbstractVector are considered to be a scalar).

Note that mapcols guarantees not to reuse the columns from df in the returned DataFrame. If f returns its argument then it gets copied before being stored.

In [75]:
mapcols(mean, x)

1×10 DataFrame
 Row │ x1        x2        x3       x4        x5        x6        x7        x8 ⋯
     │ Float64   Float64   Float64  Float64   Float64   Float64   Float64   Fl ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.450901  0.501516  0.50738  0.584501  0.493385  0.485442  0.619445  0. ⋯
                                                               3 columns omitted

### Mapping rows and columns using `eachcol` and `eachrow`
- `eachcol`: Return a DataFrameColumns object that is a vector-like that allows iterating an AbstractDataFrame column by column.
- `eachrow`: Return a DataFrameRows that iterates a data frame row by row, with each row represented as a DataFrameRow.

In [76]:
map(mean, eachcol(x)) # map a function over each column and return a vector

10-element Vector{Float64}:
 0.4509012945450682
 0.5015160723388339
 0.5073797698183354
 0.5845012201765751
 0.4933852410817835
 0.4854418159279823
 0.6194448560863139
 0.687454676782226
 0.38814273770955515
 0.44211277899501245

In [77]:
# an iteration returns a Pair with column name and values
foreach(c -> println(c[1], ": ", mean(c[2])), pairs(eachcol(x)))

x1: 0.4509012945450682
x2: 0.5015160723388339
x3: 0.5073797698183354
x4: 0.5845012201765751
x5: 0.4933852410817835
x6: 0.4854418159279823
x7: 0.6194448560863139
x8: 0.687454676782226
x9: 0.38814273770955515
x10: 0.44211277899501245


In [80]:
# now the returned value is DataFrameRow which works as a NamedTuple but is a view to a parent DataFrame
map(r -> r.x1/r.x2, eachrow(x)) # map applies a function to each value of an array and returns a new array containing the resulting values:

10-element Vector{Float64}:
 0.2983582560850262
 4.169266348339091
 1.8922518112508993
 0.3976394896336222
 0.33653159895425633
 0.7755607112245911
 1.2061622545161395
 0.5350133238662731
 0.8738331412073833
 1.781627172904762

In [81]:
# it prints like a data frame, only the caption is different so that you know the type of the object
er = eachrow(x)

10×10 DataFrameRows
 Row │ x1        x2         x3         x4        x5          x6         x7     ⋯
     │ Float64   Float64    Float64    Float64   Float64     Float64    Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.182812  0.612727   0.753226   0.680121  0.482326    0.598521   0.4567 ⋯
   2 │ 0.283253  0.0679383  0.654286   0.688255  0.84735     0.182331   0.5635
   3 │ 0.908733  0.480239   0.591067   0.518461  0.306559    0.885562   0.7646
  ⋮  │    ⋮          ⋮          ⋮         ⋮          ⋮           ⋮         ⋮   ⋱
   8 │ 0.181397  0.339051   0.0182818  0.815847  0.00507345  0.95117    0.9096
   9 │ 0.494481  0.565876   0.52434    0.629434  0.179599    0.814441   0.2759 ⋯
  10 │ 0.623516  0.34997    0.742189   0.128856  0.124592    0.864321   0.7597
                                                    4 columns and 4 rows omitted

In [82]:
er.x1 # you can access columns of a parent data frame directly

10-element Vector{Float64}:
 0.1828122356601809
 0.2832529533057573
 0.9087325273131777
 0.22612984152942328
 0.16857639077024
 0.7294842350352777
 0.7106311654577566
 0.18139666389868614
 0.4944809197469764
 0.623516012733206

In [83]:
# it prints like a data frame, only the caption is different so that you know the type of the object
ec = eachcol(x)

10×10 DataFrameColumns
 Row │ x1        x2         x3         x4        x5          x6         x7     ⋯
     │ Float64   Float64    Float64    Float64   Float64     Float64    Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.182812  0.612727   0.753226   0.680121  0.482326    0.598521   0.4567 ⋯
   2 │ 0.283253  0.0679383  0.654286   0.688255  0.84735     0.182331   0.5635
   3 │ 0.908733  0.480239   0.591067   0.518461  0.306559    0.885562   0.7646
  ⋮  │    ⋮          ⋮          ⋮         ⋮          ⋮           ⋮         ⋮   ⋱
   8 │ 0.181397  0.339051   0.0182818  0.815847  0.00507345  0.95117    0.9096
   9 │ 0.494481  0.565876   0.52434    0.629434  0.179599    0.814441   0.2759 ⋯
  10 │ 0.623516  0.34997    0.742189   0.128856  0.124592    0.864321   0.7597
                                                    4 columns and 4 rows omitted

In [84]:
ec.x1 # you can access columns of a parent data frame directly

10-element Vector{Float64}:
 0.1828122356601809
 0.2832529533057573
 0.9087325273131777
 0.22612984152942328
 0.16857639077024
 0.7294842350352777
 0.7106311654577566
 0.18139666389868614
 0.4944809197469764
 0.623516012733206

### Transposing

you can transpose a data frame using `permutedims`:

In [85]:
df = DataFrame(reshape(1:12, 3, 4), :auto)

3×4 DataFrame
 Row │ x1     x2     x3     x4    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      4      7     10
   2 │     2      5      8     11
   3 │     3      6      9     12

In [86]:
df.names = ["a", "b", "c"]

3-element Vector{String}:
 "a"
 "b"
 "c"

In [87]:
permutedims(df, :names)

4×4 DataFrame
 Row │ names   a      b      c     
     │ String  Int64  Int64  Int64 
─────┼─────────────────────────────
   1 │ x1          1      2      3
   2 │ x2          4      5      6
   3 │ x3          7      8      9
   4 │ x4         10     11     12